### ISSUE TITLE
Getting "Socket hang up" error when putting multiple blocks in one view

### ISSUE THREAD

**Issue by MikeMugu** [primaryobjects/contentblocks#8]
Hi. I pretty much have everything working on my site using your nice plugin, however when I went to add a second block to my page I started getting a "Socket hang up" error. I have traced this down to what I think is in lib/contentblocks.js line 81:

 webManagerSendSync(contentBlockItems, index + 1);

This is a recursive call to continue retrieving the block markup but appears to cause the "Socket hang up" error whenever I have more than one block on the page. 

I have tried to work around this but I am kinda new to NodeJS so have been struggling.

**Comment by primaryobjects** [comment]
It's hard to say what's wrong without seeing the view code, but you may want to take a look at the example demo [view](https://github.com/primaryobjects/contentblocks-demo/blob/master/views/index.jade), which uses multiple blocks on the same page. A socket hang up [error](http://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean) could be from your web service too (are you using your own web service?), if it's not sending back a response to the first block, or if it's refusing the connection (maybe from your user-agent?).

Your blocks should look like:

```
span(about='Paragraph1')
  div(property='content')
    if typeof(Paragraph1_content) !== 'undefined'
      != Paragraph1_content
    else
      | [edit here]
```

**Comment by MikeMugu** [comment]
Thanks for the quick response. I tried to follow the same structure as you did for your demo app and your Red-Ant REST service and thought I had things pretty much the same, but I could be missing something for sure. My view code is as follows:

    extends layout

    block content
        h1= title
        div
            #handbookMission(about='handbookMission')
                p(property='content')
                    if typeof(handbookMission_content) !== 'undefined'
                        != handbookMission_content
                    else
                        | [edit here]
    
        div
            #article1(about='article1')
                p(property='content')
                    if typeof(article1_content) !== 'undefined'
                        != article1_content
                    else
                        | [edit here]
    
    
And to be complete, my route end point is:

    exports.find = function(req, res) {
        var contentProvider = req.contentProvider;
    
        GenUtil.cleanQuery(req.query['q'].toString(), function(query, err) {
            if (err != null) {
                GenUtil.sendError(res, err.Message);
            }
            else {
                try {
                    contentProvider.find(query, function(error, items) {
                        if (!error && items != null) {
                            res.json(items);
                        }
                        else {
                            // No records found
                            res.status(404).json({ error: 'No records found.' });
                        }
                    });
                }
                catch (err) {
                    GenUtil.sendError(res, err.message);
                }
            }        
        });
    }

This code calls into a Content Provider:

    ContentProvider.prototype.find = function(query, callback) {
        this.getCollection(function(error, content_collection) {
            if (error) {
                callback(error);
            }
            else {
                content_collection.find(query).toArray(function (err, items) {
                    if (!err && items != null) {
                        callback(null, items);
                    }
                    else {
                        if (err) {
                            console.log("An error ocurred trying to find: " + err);
                        }
                        callback("No records found.");
                    }
                });
            }
        });
    };


And the route setup:

    // REST service for CMS
    router.get('/content/find', content.find);
    router.get('/content/:itemId', content.get);
    router.delete('/content/:itemId', content.delete);
    router.put('/content/:itemId', content.update);
    router.post('/content', content.create);

And the app.js that configures contentBlocks:

    var contentBlocks = require('contentblocks')(
    { 
            app: app, 
            host: 'localhost', 
            pathFind: '/content/find?q={"@subject":"[id]"}',
            pathPost: '/content', 
            pathPut: '/content/[id]', 
            pathDelete: '/content/[id]' 
    });

Like I said, I may have something off here but when debugging, it looks like the recursive call to webManagerSendSync(contentBlockItems, index + 1) causes NodeJS to consider the callback as not completing (at least, from the research I have done on this). If I take the second block out of my view, it works fine.

**Comment by primaryobjects** [comment]
I can't see anything obvious that would cause the problem.

I would first try directly calling your web service to test the calls, using something like [Advanced REST client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo). This way, you can verify the right json is coming back for the 1st and 2nd content block ids. For the 'Find' call, do an HTTP GET

Maybe also try swapping out your back-end service for the default redant service and see if this one works correctly.

```
var contentBlocks = require('contentblocks')({ app: app, host: 'red-ant.herokuapp.com', pathFind: '/v1/nest/find?q={"@subject":"[id]"}', pathPost: '/v1/nest', pathPut: '/v1/nest/[id]', pathDelete: '/v1/nest/[id]' });
```

If switching to redant works correctly, then you know something is going on in your backend service. If you still have the same problem on redant, then you know the problem is in your client code.

**Comment by MikeMugu** [comment]
Thanks again for the response. So this is what I tired:

1) Advanced REST client works as expected when requesting the URLs. The REST client seems to be working correctly.
2) I tried swapping out the back end service for the Red-Ant service, however I get an error when trying to post (the GET works when trying to find the blocks). The post error I get is:

    POST /create 404 213.424 ms - 4658
    POST /create 404 168.319 ms - 4658

I think this is because the Backbone.sync function in contentblocks.js is using the /create url. I am still going to troubleshoot a bit more. Can't seem to nail this one down. I am using Express 4.9 and probably some newer packages, not sure if any of this would have an effect.

I am going to continue troubleshooting and will let you know what I find. Thanks again for all your help.

**Comment by primaryobjects** [comment]
Yes, the post route is setup to use /create by [default](https://github.com/primaryobjects/contentblocks/blob/master/lib/managers/ControllerManager.js#L6), so your backbone code in contentblocks.js should be pointing to /create (which is the [default](https://github.com/primaryobjects/contentblocks/blob/master/scripts/contentblocks.js#L68) setting).

Another idea to try is to go into your node_modules folder and edit the contentblocks file [WebManager.js](https://github.com/primaryobjects/contentblocks/blob/master/lib/managers/WebManager.js) and stick in some console.log() statements to debug those calls. That is where it calls your REST service. Notice, the call to "request.end()" at the end of that method. That is where the connection is closed. So, you could put a console.log() statement just before the request.write() command, maybe output the "data" object and make sure it looks correct. Then a log statement after to make sure the request is ended correctly. This way you can track down where exactly that socket timeout is occurring and if the REST service is even giving back a response or not.

**Comment by MikeMugu** [comment]
So I added some logging and it looks like I am not getting a 200 response back from the server. For the home page (which has one block), I get the following:

    ************* writing out data: ""
    ************* calling reqest.end()
    ************* Done *************
    GET /content/find?q={"@subject":"<Description>"} 200 38.807 ms - 174
    GET /home 200 702.619 ms - 3340

For the Handbook page I get:

    GET /javascripts/aloha/plugins/extra/sourceview/css/sourceview.css 304 1.497 ms - -
    ************* writing out data: ""
    ************* calling reqest.end()
    ************* Done *************
    GET /content/find?q={"@subject":"<handbookMission>"} 200 3.217 ms - 2
    ************* writing out data: {}
    ************* calling reqest.end()
    ************* Done *************
    GET /content/find?q={"@subject":"<article1>"} - - ms - -

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: socket hang up
        at createHangUpError (http.js:1476:15)

Notice the second find does not include the status code back. Is it possibly a problem that I have the REST service hosted with the app instead of as separate app?

Also, the repo is here, feel free to poke around: https://github.com/MikeMugu/camsc

Thanks again for the help.

**Comment by primaryobjects** [comment]
Ok, I ran your project and was able to see the same issue. I was not able to find a cause though.

I could successfully switch to the red-ant service and it works there (after a little tweaking to change the port to 3000 in javascripts/contentblocks.js and some other tweaks to set the db path). However, when switching it back to localhost, the issue you described occurs. It's very strange.

I noticed the routing is setup a little different than the [contentblocks-demo](https://github.com/primaryobjects/contentblocks-demo) example. I'm not sure if this could be affecting it or not, but I wasn't able to get the default routes working for the ControllerManager.js. It seems like the app kept using the content.js routes instead.

If you can't make any more progress on the issue, maybe a next step could be to clone the contentblocks-demo project and switch the contentblocks service path to localhost, so it has the same route setup. Just keep the single index.js page, which already has a bunch of content blocks on it, and copy in your content.js / mongo stuff. Then see if the error happens in the demo app. Worth a try.

**Comment by primaryobjects** [comment]
I think I found the solution.

Edit node_modules/contentblocks/lib/managers/WebManager.js and change the code as follows:

```javascript
WebManager = {
    send: function (req, res, host, path, method, callback) {
        easypost.get(req, res, function (data) {
            var payload = (typeof(data) == 'object' ? JSON.stringify(data) : data);

            // Set options.
            var options = {
                host: host,
                port: 3000,
                path: path,
                method: method,
                headers: { 'content-length': Buffer.byteLength(payload) }
            };

            // Setup http method.
            var request = http.request(options, function (clientRequest) {
                // Read result.
                easypost.get(clientRequest, res, function (result) {
                    var resultObj = JSON.parse(result);
                    callback(resultObj);
                });
            });

            // Send http call.
            request.write(payload);
            request.end();
        });
    }
};
```

The key to this fix is adding the "content-length" header to the request. This fixes the socket hang up error. I will update the contentblocks library to include this fix.

**Comment by primaryobjects** [comment]
I've just published an update of contentblocks to 0.1.6 which includes this fix. I've also updated the readme with a working example of using [localhost](https://github.com/primaryobjects/contentblocks#configuration-for-localhost-rest-service) for the cms service. Along with the readme update, I checked-in a localhost [branch](https://github.com/primaryobjects/contentblocks-demo/tree/localhost) for the contentblocks demo site, so you can see exactly which changes were made to get it working locally.

**Comment by MikeMugu** [comment]
Awesome! This works for me. Thanks again for the all the help. Sorry I could not try this earlier but it is a side project that I am using to learn NodeJS.

**Comment by MikeMugu** [comment]
Interesting that the second call seemed to be passing JSON data, I noticed that in the logs but was not sure what it could mean. Also, thanks for updating the localhost example, my next step was going to be to separate the REST service from the client, which hindsight is probably not a bad idea anyway. But I am glad you figured out the root cause.
