### ISSUE TITLE
Aloha.css missing

### ISSUE THREAD

**Issue by kmturley** [primaryobjects/contentblocks#9]
This file doesn't exists anymore :(
http://cdn.aloha-editor.org/latest/css/aloha.css

**Comment by primaryobjects** [comment]
It seems the Aloha Editor has been [discontinued](http://www.alohaeditor.org/). However, you can probably still pull the css from their GitHub repository here https://github.com/alohaeditor/Aloha-Editor/tree/dev/src/css

**Comment by kmturley** [comment]
Great! are you going to update the README.md too? currently it links to the file!

**Comment by primaryobjects** [comment]
I've updated the code with a local copy of aloha.css to replace the CDN. The README.md has also been updated. See https://github.com/primaryobjects/contentblocks/commit/dc8a86400dd894fc888c8f9c0eb7b795e0dc7a48
:)

**Comment by kmturley** [comment]
nice, thanks for the fast turnaround!
